### ISSUE TITLE
Container Process Start Failure

### ISSUE THREAD

**Issue by wapplegate** [Comcast/trivy-resource#3]
A team member is trying to use this resource in a concourse pipeline and we're seeing this issue:

`run check: start process: backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:380: starting container process caused: exec: \"/opt/resource/check\": permission denied","Handle":"","ProcessID":"","Binary":""}`

We're thinking this was an issue with the Docker image build? Have you seen this before?

**Comment by christiangebhard** [comment]
We are facing a similar issue, adding this line to the end of the Dockerfile fixes it (not sure if this is the preferred way to add the necessary permissions though)

`RUN chmod +x /opt/resource/*`

**Comment by hriprsd** [comment]
Thanks @wapplegate and @christiangebhard 
Locally while testing I had the proper permissions added, missed that in Dockerfile. 
Good catch. 
#4 Will fix this issue. Thanks for reporting this. 😄
